name: Postman API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🧰 Install Newman & Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: 🧪 Run all Postman Collections
        run: |
          mkdir -p newman-report
          for file in postman/*.json; do
            name=$(basename "$file" .json)
            echo "Running collection: $name"
            newman run "$file" \
              --globals postman/globals.json \
              --reporters cli,htmlextra \
              --reporter-htmlextra-export "newman-report/${name}-report.html"
          done

      - name: 📤 Upload Newman HTML Report
        uses: actions/upload-artifact@v4
        with:
            name: postman-html-report
            path: newman-report/
